import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Poppins({
  weight: ['200', '300', '400', '600', '800'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Enjoy The nature",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        nav
        {children}
        footer
      </body>
    </html>
  );
}
